import { cn } from "@/lib/utils";

const TOOLTIP = "Conteúdo gerado por IA — pode conter erros. Revise antes de agir.";
const LABEL = "Conteúdo gerado por IA";

interface AiBadgeProps {
  className?: string;
  size?: "sm" | "xs";
}

/**
 * AI-provenance marker (Decision D-015). Signals that a feature or its output is
 * generated by IA. Single source of AI-provenance semantics — apply at every AI
 * surface instead of ad-hoc "(IA)" labels.
 *
 * Accessibility: the visible "IA" text plus `aria-label` give the badge an
 * accessible name; the decorative sparkles icon is `aria-hidden`; the tooltip is
 * a native `title` (keyboard/touch reachable as plain text, no library needed).
 */
export function AiBadge({ className, size = "xs" }: AiBadgeProps) {
  const sizeClasses =
    size === "sm" ? "text-xs px-2 py-0.5 gap-1" : "text-[10px] px-1.5 py-0.5 gap-0.5";
  return (
    <span
      role="img"
      aria-label={LABEL}
      title={TOOLTIP}
      className={cn(
        "inline-flex items-center rounded-full border border-transparent bg-violet-100 font-semibold text-violet-700 align-middle",
        sizeClasses,
        className,
      )}
    >
      <SparklesIcon />
      IA
    </span>
  );
}

function SparklesIcon() {
  return (
    <svg
      aria-hidden="true"
      viewBox="0 0 24 24"
      fill="currentColor"
      className="h-3 w-3 shrink-0"
    >
      <path d="M12 3l1.6 4.6L18 9.2l-4.4 1.6L12 15.4l-1.6-4.6L6 9.2l4.4-1.6L12 3z" />
      <path d="M18 14l.9 2.5L21 17.4l-2.1.9L18 21l-.9-2.7L15 17.4l2.1-.9L18 14z" />
    </svg>
  );
}
